interface HoroscopeSegments {
  focus: string[];
  advice: string[];
  caution: string[];
  reflection: string[];
}

const HOROSCOPE_SEGMENTS: Record<string, HoroscopeSegments> = {
  aries: {
    focus: [
      "A quiet determination guides your morning, turning your attention toward unfinished tasks.",
      "You may feel a subtle urge to step forward and take the lead on a group project.",
      "Today brings an invitation to pause and assess your current momentum.",
      "Your natural drive is present, though it finds its best outlet in structured effort.",
      "Conversations today may challenge you to explain your perspective more patiently.",
      "A focus on practical organization helps clarify your thoughts.",
      "Today brings opportunities to practice patience rather than pushing for immediate results.",
      "Your attention is drawn to collaborative projects that require steady cooperation.",
      "A calm clarity is available to you if you step back from busy routines.",
      "Today favors personal projects that require concentration and deliberate effort.",
    ],
    advice: [
      "Focus on one careful conversation and choose clarity over speed.",
      "Take time to write down your goals before committing to new plans.",
      "Spend some time in quiet reflection before making your next move.",
      "Work on establishing a steady rhythm rather than rushing to the finish line.",
      "Listening carefully to a peer will reveal insights you might have missed.",
      "Dedicate a quiet hour to organizing your workspace or schedule.",
      "Speak from a place of calm understanding rather than quick reaction.",
      "Collaborate with someone whose skills complement your own.",
      "Break a large task down into small, manageable steps.",
      "Pause to appreciate how far you have already come.",
    ],
    caution: [
      "Guard against a tendency to respond too quickly when challenged.",
      "Avoid taking on more commitments than your schedule realistically allows.",
      "Try not to let minor delays disrupt your peace of mind.",
      "Be mindful of pushing for answers before others are ready to respond.",
      "Avoid making assumptions about someone's intentions; ask directly instead.",
      "Guard against impatience when things take longer than expected.",
      "Try not to neglect small details in your haste to complete a project.",
      "Resist the temptation to force progress when a pause is more appropriate.",
      "Avoid overextending yourself to meet someone else's rapid pace.",
      "Be careful not to let temporary frustrations dictate your choices.",
    ],
    reflection: [
      "True progress is often quiet, built step by step through deliberate action.",
      "Growth is rarely a straight line; give yourself room to learn.",
      "Clarity comes when we allow our thoughts to settle.",
      "A thoughtful pause now can prevent misunderstandings later.",
      "Wisdom is found in knowing when to act and when to listen.",
      "Small, steady efforts yield the most sustainable results.",
      "Balance is not a static state, but a continuous adjustment.",
      "Self-awareness is the first step toward meaningful connection.",
      "Trust that taking your time is a valid form of progress.",
      "Sometimes the most productive choice is simply to rest.",
    ],
  },
  taurus: {
    focus: [
      "A slow, steady rhythm feels natural today, letting you focus on simple tasks.",
      "You might find comfort in sorting through your immediate surroundings and creating order.",
      "Today highlights the value of physical stability and a grounded presence.",
      "Your attention shifts toward long-term security and practical planning.",
      "A quiet focus on refining existing work serves you better than seeking novelty.",
      "Connections with nature or sensory details bring a sense of calm.",
      "Today asks you to honor your need for steady, uninterrupted progress.",
      "You may feel a strong appreciation for practical crafts and handmade details.",
      "A calm clarity is found in focusing on one physical project at a time.",
      "Today favors reviewing your resources and setting realistic boundaries.",
    ],
    advice: [
      "Take time to enjoy a quiet lunch or a walk outside to refresh your senses.",
      "Review your practical budgets or schedules with a patient eye.",
      "Offer steady, quiet support to a colleague who seems overwhelmed.",
      "Focus on completing one task thoroughly before moving to the next.",
      "Practice flexibility when small adjustments to your plan are suggested.",
      "Spend a few minutes organizing your physical desk or room.",
      "Express appreciation for the reliable people in your life.",
      "Choose simplicity over complexity in your daily tasks.",
      "Set a gentle pace for your day and protect your focus.",
      "Ground your choices in concrete facts rather than abstract assumptions.",
    ],
    caution: [
      "Guard against a tendency to resist change simply because it is unfamiliar.",
      "Avoid overindulging in comfort habits to escape daily responsibilities.",
      "Try not to let stubbornness lock you into an unproductive debate.",
      "Be mindful of delaying decisions because they feel slightly uncomfortable.",
      "Avoid holding onto objects or habits that no longer serve a useful purpose.",
      "Guard against expecting others to move at your exact speed.",
      "Try not to neglect creative possibilities in favor of rigid routines.",
      "Resist the urge to push through fatigue; rest when your body asks for it.",
      "Avoid mistaking a temporary setback for a permanent failure.",
      "Be careful not to shut out valuable feedback from trusted friends.",
    ],
    reflection: [
      "Stability is built from small, consistent habits practiced day by day.",
      "Patience is not just waiting; it is a calm confidence in the process.",
      "True value is often found in things that take time to grow.",
      "A grounded mind can weather any passing emotional storm.",
      "Simplicity is a form of clarity that brings immediate peace.",
      "Nurturing your immediate environment helps nurture your mind.",
      "Adaptability and strength are not opposites; they support each other.",
      "Respecting your physical limits is a key part of self-care.",
      "Quiet endurance is a quiet but powerful force.",
      "The foundations we build today support our choices tomorrow.",
    ],
  },
  gemini: {
    focus: [
      "Your curiosity is active today, leading you toward fresh questions and ideas.",
      "Conversations flow easily, bringing opportunities to share thoughts and learn.",
      "A lively mental rhythm encourages you to explore multiple topics.",
      "Today highlights the value of adaptability and quick, observant thinking.",
      "You may find yourself drawn to writing, organizing notes, or replying to messages.",
      "Connecting with colleagues brings a constructive exchange of viewpoints.",
      "Today favors quick research and gathering details on a topic of interest.",
      "A lighthearted mood makes it easier to navigate small daily challenges.",
      "Your mind is active, seeking patterns and connections in what you read.",
      "Today brings an invitation to share your ideas in a clear, collaborative way.",
    ],
    advice: [
      "Focus on summarizing your thoughts to keep your communication concise.",
      "Take regular short breaks to prevent your mind from feeling scattered.",
      "Listen twice as much as you speak in your key meetings today.",
      "Write down your sudden ideas so you can explore them systematically later.",
      "Seek out a fresh perspective from someone outside your immediate circle.",
      "Dedicate a block of time to replying to pending messages.",
      "Use visual sketches or notes to organize a complex task.",
      "Share a helpful reference or article with a peer who needs it.",
      "Practice saying no to additional tasks to protect your active projects.",
      "Ground your intellectual curious steps in real, practical actions.",
    ],
    caution: [
      "Guard against skimming the surface when a deeper look is required.",
      "Avoid committing to multiple projects without checking your availability.",
      "Try not to let sudden distractions pull you away from key tasks.",
      "Be mindful of sharing unverified details in casual discussions.",
      "Avoid overthinking simple decisions; sometimes a practical choice is best.",
      "Guard against starting new projects before completing current ones.",
      "Try not to let a busy schedule turn into mental exhaustion.",
      "Resist the urge to debate minor points when agreement is close.",
      "Avoid promising immediate answers when you need time to research.",
      "Be careful not to neglect quiet reflection in favor of constant updates.",
    ],
    reflection: [
      "True understanding is built from active listening, not just speaking.",
      "Clarity is found when we filter out noise to focus on signal.",
      "Adaptability allows us to flow with change without losing our direction.",
      "A thoughtful conversation is a two-way street of mutual respect.",
      "Curiosity keeps our minds open to continuous learning.",
      "Words have power; choose them with care and kindness.",
      "Focus is the art of saying no to a hundred good ideas.",
      "Mental rest is just as important as physical rest.",
      "Sharing knowledge is a simple way to build community.",
      "A flexible mind can find solutions where others see obstacles.",
    ],
  },
  cancer: {
    focus: [
      "Your intuition is a quiet guide today, drawing your attention to feelings.",
      "Creating a comfortable and organized home space feels rewarding today.",
      "A sensitive awareness of others' moods helps you navigate interactions.",
      "Today highlights the value of emotional boundaries and self-care.",
      "You may feel a natural draw toward nostalgic memories or old archives.",
      "Connections with close friends or family members bring warmth.",
      "Today favors quiet, focused tasks that allow you to work at your own pace.",
      "Your nurturing side is active, finding expression in quiet support.",
      "A calm clarity is found by checking in with your internal feelings.",
      "Today brings an invitation to protect and recharge your personal reserves.",
    ],
    advice: [
      "Take time to check in on your emotional comfort during busy hours.",
      "Create a small comfort ritual in your evening to unwind.",
      "Listen to your physical responses; they often point to what you need.",
      "Set gentle but clear boundaries on your time and energy today.",
      "Offer a quiet word of support to a colleague who is struggling.",
      "Dedicate some time to cooking a nourishing meal or organizing your home.",
      "Write down your thoughts in a private journal to process them.",
      "Connect with a trusted friend for a calm, honest conversation.",
      "Protect your schedule from sudden, unnecessary demands.",
      "Focus on creating a supportive environment for your current tasks.",
    ],
    caution: [
      "Guard against taking casual remarks as personal criticism.",
      "Avoid retreating into silence when a clear conversation is needed.",
      "Try not to let past frustrations dictate your present choices.",
      "Be mindful of taking on other people's problems as your own.",
      "Avoid overprotecting yourself to the point of isolation.",
      "Guard against holding onto old habits that limit your growth.",
      "Try not to let emotional worries overshadow practical facts.",
      "Resist the temptation to please others at the cost of your peace.",
      "Avoid rush decisions when your intuition asks you to wait.",
      "Be careful not to let exhaustion cloud your natural clarity.",
    ],
    reflection: [
      "True strength is found in acknowledging and respecting our sensitivity.",
      "Boundaries are not walls; they are gates that let the right things in.",
      "Nurturing ourselves allows us to support others more sustainably.",
      "Quiet spaces are essential for listening to our inner guidance.",
      "Letting go of past burdens creates space for new understandings.",
      "Emotional depth is a source of wisdom and deep connection.",
      "Gentle persistence often succeeds where force fails.",
      "Trusting your pace is a vital form of self-respect.",
      "Kindness starting with yourself is the foundation of balance.",
      "Home is not just a place, but a state of inner peace.",
    ],
  },
  leo: {
    focus: [
      "Your natural warmth shines today, encouraging positive connections.",
      "Creative self-expression finds a quiet, focused outlet in your work.",
      "Today highlights the value of leading with generosity and encouragement.",
      "A focus on collaborative projects brings out your best cooperative skills.",
      "You may feel a steady confidence in presenting your ideas to others.",
      "Organizing a group activity or project is supported by your clear outlook.",
      "Today favors sharing appreciation for the efforts of those around you.",
      "A playful approach to problem-solving helps break through challenges.",
      "Your drive to build and share is strong, guided by steady purpose.",
      "Today brings an invitation to step forward and offer practical guidance.",
    ],
    advice: [
      "Make a conscious effort to highlight a colleague's excellent work.",
      "Dedicate time to a creative hobby that brings you simple joy.",
      "Offer warm, constructive support in your team discussions.",
      "Keep your plans simple and focus on execution rather than show.",
      "Speak clearly and invite others to share their perspectives too.",
      "Spend a few minutes organizing a shared resource or folder.",
      "Practice humility by listening carefully to constructive feedback.",
      "Express your gratitude to someone who supported you recently.",
      "Focus on the core message of your presentation or ideas.",
      "Walk with a calm confidence that doesn't need external validation.",
    ],
    caution: [
      "Guard against a tendency to dominate discussions or decisions.",
      "Avoid seeking constant validation from outside sources.",
      "Try not to let pride prevent you from asking for help.",
      "Be mindful of overcommitting to make a positive impression.",
      "Avoid reacting defensively when alternatives are proposed.",
      "Guard against taking minor oversights as personal slights.",
      "Try not to neglect quiet preparation in favor of active action.",
      "Resist the temptation to make grand gestures when simple ones work.",
      "Avoid ignoring the subtle details of a project in your excitement.",
      "Be careful not to exhaust your energy reserves in group activities.",
    ],
    reflection: [
      "True leadership is about lifting others up and sharing the spotlight.",
      "Creative joy is found in the process, not just the final result.",
      "Generosity of spirit builds lasting, genuine connections.",
      "Calm self-assurance has a quiet power that needs no display.",
      "Respecting others' contributions enriches our own work.",
      "Growth is supported when we balance pride with a willingness to learn.",
      "A warm heart can diffuse the most complex disagreements.",
      "True confidence allows room for others to shine alongside you.",
      "Small acts of encouragement can create big ripples of goodwill.",
      "Inner strength is nurtured through quiet, honest self-assessment.",
    ],
  },
  virgo: {
    focus: [
      "A quiet attention to detail helps you resolve pending issues today.",
      "Organizing your schedule or space brings a satisfying sense of clarity.",
      "Today highlights the value of practical service and steady craftsmanship.",
      "A focus on refining workflows leads to useful adjustments.",
      "You may find satisfaction in proofreading, editing, or sorting data.",
      "Connections with colleagues focus on practical cooperation and support.",
      "Today favors steady, methodical research on a specific task.",
      "Your analytical mind is sharp, identifying patterns and solutions.",
      "A calm patience helps you address small errors before they grow.",
      "Today brings an invitation to improve your daily habits systematically.",
    ],
    advice: [
      "Break down a complex project into a detailed, step-by-step list.",
      "Practice self-compassion when things do not go exactly as planned.",
      "Dedicate time to simplifying a cluttered section of your workspace.",
      "Focus on serving your team through quiet, efficient support.",
      "Take regular breaks to rest your eyes and clear your thoughts.",
      "Ground your suggestions in clear facts and organized details.",
      "Set aside a few minutes to clean up your digital desktop.",
      "Choose progress over perfection in your active tasks today.",
      "Seek out practical tools that make your routine more efficient.",
      "Let your actions speak for themselves through careful craft.",
    ],
    caution: [
      "Guard against getting lost in details at the cost of the main goal.",
      "Avoid excessive self-criticism or judging your progress too harshly.",
      "Try not to offer advice unless it is requested by others.",
      "Be mindful of letting worry about minor errors disrupt your peace.",
      "Avoid overanalyzing simple situations or choices today.",
      "Guard against assuming that only your method is correct.",
      "Try not to let daily checklists turn into rigid obligations.",
      "Resist the urge to fix things that are already working well.",
      "Avoid pushing yourself beyond your limits to meet impossible standards.",
      "Be careful not to let analytical focus block intuitive insights.",
    ],
    reflection: [
      "Progress is built on small, incremental improvements made consistently.",
      "Simplicity is a form of sophistication in organizing our lives.",
      "True service is quiet, reliable, and grounded in mutual respect.",
      "Letting go of perfection allows us to appreciate real progress.",
      "A calm mind is the most effective tool for resolving complexity.",
      "Wisdom lies in knowing which details matter and which to let go.",
      "Sustainable habits are built with patience and self-compassion.",
      "Order is a tool to create freedom, not a cage to limit it.",
      "Collaborative success relies on each person doing their small part.",
      "A quiet dedication to quality is a powerful form of integrity.",
    ],
  },
  libra: {
    focus: [
      "Today focuses on balance, inviting you to create harmony in your space.",
      "Collaborative tasks are supported, bringing pleasant joint progress.",
      "A natural appreciation for aesthetics helps you style your surroundings.",
      "Today highlights the value of fair listening and open-minded views.",
      "You may find yourself acting as a quiet mediator in a discussion.",
      "Connections with partners or peers are warm and supportive.",
      "Today favors structured discussions where all sides are considered.",
      "A focus on steady compromises helps resolve recent small differences.",
      "Your mind seeks symmetry and calm order in daily routines.",
      "Today brings an invitation to align your tasks with your core values.",
    ],
    advice: [
      "Take time to listen to all perspectives before sharing your view.",
      "Design a clean, visually peaceful arrangement for your desk.",
      "Practice setting clear, kind boundaries with colleagues.",
      "Focus on tasks that require cooperative planning or joint input.",
      "Dedicate a moment to balancing your daily work and rest hours.",
      "Express your appreciation for a partner's reliable input.",
      "Walk away from heated debates to seek a neutral middle ground.",
      "Put your thoughts in writing to clarify your personal position.",
      "Choose options that promote sustainable, long-term balance.",
      "Ground your choices in fairness and objective observation.",
    ],
    caution: [
      "Guard against avoiding necessary choices to keep a temporary peace.",
      "Avoid agreeing with opinions simply to prevent minor friction.",
      "Try not to let indecisiveness stall a simple daily project.",
      "Be mindful of neglecting your own needs to support others.",
      "Avoid overcommitting yourself to maintain social harmony.",
      "Guard against letting other people's vibes dictate your mood.",
      "Try not to overthink the social dynamics of your team.",
      "Resist the urge to please everyone; focus on what is fair.",
      "Avoid rushing a decision just to get the process over with.",
      "Be careful not to lose your personal focus in collaborative efforts.",
    ],
    reflection: [
      "Balance is not a destination, but a series of mindful adjustments.",
      "Harmony is built on mutual respect and open, honest dialogue.",
      "True fairness requires us to honor our own needs as well as others'.",
      "A peaceful environment supports a clear and focused mind.",
      "Diplomacy is the art of letting everyone speak and be heard.",
      "Strength is found in gentle consistency and quiet boundaries.",
      "Respecting differences is the foundation of cooperative growth.",
      "A clear decision brings its own form of peaceful resolution.",
      "Cooperation is most effective when each partner stands firm.",
      "Inner peace starts when we stop trying to control external views.",
    ],
  },
  scorpio: {
    focus: [
      "Today brings intense focus, letting you dive deep into complex work.",
      "A perceptive mindset helps you read between the lines in discussions.",
      "Today highlights the value of trust, privacy, and quiet determination.",
      "A focus on research or investigation yields useful insights.",
      "You may feel a natural draw toward solving puzzles or organizing data.",
      "Connections with close peers are direct, meaningful, and honest.",
      "Today favors working independently on tasks that require depth.",
      "Your determination is strong, helping you push through roadblocks.",
      "A calm clarity is found by releasing habits that hold you back.",
      "Today brings an invitation to build trust through steady honesty.",
    ],
    advice: [
      "Channel your focus into one major project that needs depth.",
      "Keep your key projects confidential until they are ready to share.",
      "Listen to your gut feelings during important conversations today.",
      "Practice letting go of small grudges to clear your mental space.",
      "Work in a quiet environment to protect your concentration.",
      "Share your observations directly but calmly with trusted peers.",
      "Dedicate a few minutes to decluttering your digital files.",
      "Use your analytical focus to resolve a long-standing issue.",
      "Focus on the core truth of a matter rather than surface views.",
      "Ground your intensity in quiet, step-by-step daily tasks.",
    ],
    caution: [
      "Guard against suspicious thoughts when simple explanations exist.",
      "Avoid trying to control outcomes that depend on other people.",
      "Try not to let intense focus turn into stubborn persistence on a mistake.",
      "Be mindful of keeping secrets that block healthy team cooperation.",
      "Avoid reacting with defensive silence when feedback is offered.",
      "Guard against holding onto old frustrations that drain your energy.",
      "Try not to let power struggles disrupt your working relationships.",
      "Resist the temptation to analyze everyone's hidden motives today.",
      "Avoid pushing yourself to exhaustion on a single task.",
      "Be careful not to let intensity build up; take breaks to breathe.",
    ],
    reflection: [
      "True strength is found in vulnerability and building honest trust.",
      "Transformation begins when we let go of what we no longer need.",
      "Depth is a gift, but it must be balanced with practical daily routines.",
      "Focus is most powerful when guided by quiet, patient intent.",
      "Trust is built slowly, step by step, through consistent action.",
      "Perception is a tool for understanding, not a weapon for defense.",
      "Quiet determination achieves what loud actions cannot.",
      "Releasing control allows new and better options to emerge.",
      "Wisdom lies in recognizing the difference between stubbornness and resolve.",
      "Inner peace comes from accepting things as they are right now.",
    ],
  },
  sagittarius: {
    focus: [
      "An open, curious outlook helps you see the big picture today.",
      "A desire for fresh learning encourages you to research new topics.",
      "Today highlights the value of broad perspectives and honest sharing.",
      "A focus on forward-looking ideas brings constructive enthusiasm.",
      "You may feel a natural urge to explore creative options in work.",
      "Connections with peers are lighthearted, open, and conversational.",
      "Today favors planning general goals rather than parsing details.",
      "A cheerful determination helps you navigate small delays with ease.",
      "Your mind is active, seeking meaning and context in your tasks.",
      "Today brings an invitation to share your knowledge with a peer.",
    ],
    advice: [
      "Focus on connecting your daily tasks to your larger values.",
      "Dedicate a few minutes to reading about a topic outside your field.",
      "Share an encouraging insight or reference with your team.",
      "Use a checklist to ensure you do not miss small, critical steps.",
      "Practice listening to detailed suggestions with a patient mind.",
      "Spend a moment outside to appreciate a broader visual space.",
      "Keep your spoken words direct, kind, and constructive today.",
      "Break down grand ideas into simple, immediate target tasks.",
      "Seek out collaborations that expand your general approach.",
      "Ground your enthusiasm in steady, realistic daily routines.",
    ],
    caution: [
      "Guard against promising more than you can realistically deliver.",
      "Avoid skipping small, boring details in your rush to build.",
      "Try not to let restlessness disrupt a task that requires focus.",
      "Be mindful of sharing opinions as if they were established facts.",
      "Avoid taking on too many tasks out of sudden enthusiasm.",
      "Guard against dismissing structured methods simply because they are old.",
      "Try not to let impatience with details affect your final quality.",
      "Resist the temptation to wander off task when consistency is needed.",
      "Avoid overlooking current commitments in favor of future plans.",
      "Be careful not to let bluntness override your natural kindness.",
    ],
    reflection: [
      "True wisdom is found in continuous learning and open conversation.",
      "Perspective is a lens that helps us see opportunities in obstacles.",
      "Freedom is most satisfying when balanced with reliable commitments.",
      "A cheerful attitude is a quiet force that supports team morale.",
      "Growth comes when we test our views against practical results.",
      "Simplicity in execution makes room for big ideas to grow.",
      "Honesty must be balanced with empathy to build true trust.",
      "A long journey is completed by taking one small step at a time.",
      "Learning from others is a sign of personal maturity and strength.",
      "Trusting the process helps us stay calm during temporary delays.",
    ],
  },
  capricorn: {
    focus: [
      "Structured, methodical energy supports your steady progress today.",
      "A focus on long-term responsibilities brings clarity to your tasks.",
      "Today highlights the value of discipline, patience, and quality work.",
      "An organized review of your goals helps structure your week.",
      "You may feel a steady satisfaction in meeting key milestones.",
      "Connections with peers focus on professional support and cooperation.",
      "Today favors quiet, focused efforts on complex, demanding tasks.",
      "Your focus is practical, aiming for reliable and lasting results.",
      "A calm persistence helps you navigate challenging details with ease.",
      "Today brings an invitation to lead by quiet, consistent example.",
    ],
    advice: [
      "Focus on establishing a clean, structured schedule for your day.",
      "Take time to check your posture and breathe deeply during work.",
      "Dedicate a block of time to reviewing your project progress.",
      "Offer steady, quiet encouragement to a colleague facing delays.",
      "Practice delegation rather than trying to handle everything alone.",
      "Spend a few minutes organizing your primary files or workspace.",
      "Ground your arguments in clear, historical data and facts.",
      "Keep your actions focused on quality rather than speed today.",
      "Schedule regular breaks to avoid build-up of mental strain.",
      "Walk with a calm resolve, trusting the foundations you have built.",
    ],
    caution: [
      "Guard against a tendency to judge your progress too critically.",
      "Avoid working through breaks at the expense of your wellness.",
      "Try not to let a rigid schedule block creative adjustments.",
      "Be mindful of assuming all responsibilities must rest on you.",
      "Avoid expressing skepticism before hearing a fresh concept out.",
      "Guard against letting professional stress affect your close bonds.",
      "Try not to let temporary delays look like long-term blockages.",
      "Resist the urge to push through exhaustion; choose rest instead.",
      "Avoid focusing solely on work; make room for personal comfort.",
      "Be careful not to let perfectionism delay the release of your work.",
    ],
    reflection: [
      "Sustainable success is built step by step, with patience and care.",
      "Integrity is doing quality work even when no one is watching.",
      "True authority is quiet, reliable, and grounded in mutual respect.",
      "Resting when needed is a key part of long-term efficiency.",
      "A structured mind can navigate any chaotic external situation.",
      "Progress is often quiet and invisible before it becomes clear.",
      "Respecting your limits is a sign of personal wisdom and strength.",
      "The most valuable structures are those that support everyone.",
      "Small, consistent efforts create the most durable foundations.",
      "Wisdom is knowing what is within your control and what is not.",
    ],
  },
  aquarius: {
    focus: [
      "Your inventive mind is active, looking at tasks from fresh angles.",
      "Collaborative projects or community discussions are supported today.",
      "Today highlights the value of independent thinking and original ideas.",
      "A focus on forward-looking concepts brings helpful conversations.",
      "You may feel a natural draw toward learning about modern methods.",
      "Connections with peers are friendly, objective, and collaborative.",
      "Today favors sharing thoughts on shared team improvements.",
      "A quiet confidence helps you walk your own path in daily tasks.",
      "Your mind seeks original solutions to long-standing challenges.",
      "Today brings an invitation to connect with like-minded colleagues.",
    ],
    advice: [
      "Take a moment to write down your most unconventional ideas.",
      "Spend time listening to team members' suggestions with open ears.",
      "Dedicate some time to a collaborative or community project.",
      "Practice balancing your logical analysis with emotional warmth.",
      "Use clear, simple language to share your modern concepts.",
      "Set aside a few minutes to clean your digital tools or software.",
      "Offer objective, calm feedback when requested by a peer.",
      "Seek out perspectives that challenge your typical way of thinking.",
      "Focus on the collective benefits of your current project.",
      "Ground your unique plans in step-by-step, practical actions.",
    ],
    caution: [
      "Guard against detached behavior that makes others feel ignored.",
      "Avoid arguing for a point simply to be different from the group.",
      "Try not to let theoretical ideas delay practical implementation.",
      "Be mindful of neglecting personal details in favor of group goals.",
      "Avoid reacting impatiently when others move at a slower pace.",
      "Guard against holding onto intellectual pride during team talks.",
      "Try not to let stubbornness disguise itself as independent thinking.",
      "Resist the temptation to distance yourself when collaboration gets busy.",
      "Avoid ignoring the emotional undertones of a key meeting.",
      "Be careful not to overcomplicate simple issues with too much theory.",
    ],
    reflection: [
      "Real collaboration is built on respecting each person's unique voice.",
      "Original ideas are most valuable when they serve a practical purpose.",
      "Independence is strength, but community is where we build together.",
      "A clear, objective mind can find order in any complex debate.",
      "Growth comes when we share both our thoughts and our care.",
      "True progress is about building paths that include everyone.",
      "Staying open to alternative views expands our own understanding.",
      "A quiet conversation can spark a fresh way of looking at the world.",
      "Trusting your unique perspective is a vital form of self-expression.",
      "Inner peace is found when we align our work with our ideals.",
    ],
  },
  pisces: {
    focus: [
      "A quiet, intuitive day invites you to work at a reflective pace.",
      "Creative imagination finds a peaceful, constructive outlet today.",
      "Today highlights the value of empathy, patience, and calm listening.",
      "A focus on supportive, quiet tasks brings a sense of fulfillment.",
      "You may feel a natural sensitivity to the feelings of those around you.",
      "Connections with close friends are warm, gentle, and understanding.",
      "Today favors independent tasks that allow for artistic input.",
      "A calm clarity is found by letting go of worries outside your control.",
      "Your mind processes details through patterns and quiet insights.",
      "Today brings an invitation to protect and restore your inner quiet.",
    ],
    advice: [
      "Dedicate a block of time to journaling or creative thinking today.",
      "Check in on your energy levels and take quiet breaks when needed.",
      "Offer a listening ear to a colleague who needs quiet support.",
      "Set clear, kind boundaries to protect your focus from distraction.",
      "Focus on activities that bring you a sense of emotional calm.",
      "Spend a few minutes near natural light or plants to recharge.",
      "Ground your creative ideas in concrete, draft versions on paper.",
      "Let go of the need to control every detail of today's schedule.",
      "Practice active listening without feeling you must solve every issue.",
      "Walk with a gentle presence, treating yourself with patient kindness.",
    ],
    caution: [
      "Guard against escaping into daydreaming at the expense of tasks.",
      "Avoid absorbing the stress or negative vibes of people around you.",
      "Try not to let vague worries distract you from clear facts.",
      "Be mindful of saying yes to requests when your energy is low.",
      "Avoid taking other people's criticism as a measure of your worth.",
      "Guard against delaying necessary actions because they feel heavy.",
      "Try not to let boundaries blur when team cooperation gets complex.",
      "Resist the temptation to hide away when a brief check-in is needed.",
      "Avoid making assumptions about outcomes; verify details directly.",
      "Be careful not to neglect your physical comfort while focused.",
    ],
    reflection: [
      "Intuition is a quiet voice; we must create calm to hear it.",
      "Sensitivity is a source of understanding and deep connection.",
      "Letting go of external worry makes room for internal peace.",
      "Sustainable progress is made when we honor our natural rhythm.",
      "A gentle approach can resolve tensions that force cannot move.",
      "Creativity is the mind playing in a space of complete freedom.",
      "Protecting your peace is a vital step toward helping others.",
      "True connection is built on quiet trust and mutual patience.",
      "Small acts of empathy create a warm and supportive workspace.",
      "Inner quiet is a sanctuary you can return to at any moment.",
    ],
  },
};

function getSeed(str: string, date: Date): number {
  const y = date.getFullYear();
  const m = date.getMonth();
  const d = date.getDate();
  const inputStr = `${str.toLowerCase()}-${y}-${m}-${d}`;
  let hash = 0;
  for (let i = 0; i < inputStr.length; i++) {
    hash = (hash << 5) - hash + inputStr.charCodeAt(i);
    hash |= 0;
  }
  return Math.abs(hash);
}

export function getDailyHoroscope(signName: string, date: Date = new Date()): string {
  const key = signName.toLowerCase();
  const segments = HOROSCOPE_SEGMENTS[key] || HOROSCOPE_SEGMENTS.aries;
  const seed = getSeed(signName, date);

  const focusIdx = seed % 10;
  const adviceIdx = Math.floor(seed / 10) % 10;
  const cautionIdx = Math.floor(seed / 100) % 10;
  const reflectionIdx = Math.floor(seed / 1000) % 10;

  const focus = segments.focus[focusIdx];
  const advice = segments.advice[adviceIdx];
  const caution = segments.caution[cautionIdx];
  const reflection = segments.reflection[reflectionIdx];

  return `${focus} ${advice} ${caution} ${reflection}`;
}
