/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTransitsRouteImport } from './routes/api/transits'
import { Route as ApiAstroReportRouteImport } from './routes/api/astro-report'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTransitsRoute = ApiTransitsRouteImport.update({
  id: '/api/transits',
  path: '/api/transits',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAstroReportRoute = ApiAstroReportRouteImport.update({
  id: '/api/astro-report',
  path: '/api/astro-report',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/astro-report': typeof ApiAstroReportRoute
  '/api/transits': typeof ApiTransitsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/astro-report': typeof ApiAstroReportRoute
  '/api/transits': typeof ApiTransitsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/astro-report': typeof ApiAstroReportRoute
  '/api/transits': typeof ApiTransitsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/astro-report' | '/api/transits'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/astro-report' | '/api/transits'
  id: '__root__' | '/' | '/api/astro-report' | '/api/transits'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAstroReportRoute: typeof ApiAstroReportRoute
  ApiTransitsRoute: typeof ApiTransitsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transits': {
      id: '/api/transits'
      path: '/api/transits'
      fullPath: '/api/transits'
      preLoaderRoute: typeof ApiTransitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/astro-report': {
      id: '/api/astro-report'
      path: '/api/astro-report'
      fullPath: '/api/astro-report'
      preLoaderRoute: typeof ApiAstroReportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAstroReportRoute: ApiAstroReportRoute,
  ApiTransitsRoute: ApiTransitsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
